/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as MoreRouteImport } from './routes/more'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as CustomersIdIndexRouteImport } from './routes/customers.$id.index'
import { Route as CustomersIdBillRouteImport } from './routes/customers.$id.bill'
import { Route as CustomersIdEditRouteImport } from './routes/customers.$id.edit'
import { Route as CustomersIdLedgerRouteImport } from './routes/customers.$id.ledger'
import { Route as CustomersIdPaymentRouteImport } from './routes/customers.$id.payment'
import { Route as CustomersIdPaymentsRouteImport } from './routes/customers.$id.payments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdIndexRoute = CustomersIdIndexRouteImport.update({
  id: '/customers/$id/',
  path: '/customers/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdBillRoute = CustomersIdBillRouteImport.update({
  id: '/customers/$id/bill',
  path: '/customers/$id/bill',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdEditRoute = CustomersIdEditRouteImport.update({
  id: '/customers/$id/edit',
  path: '/customers/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdLedgerRoute = CustomersIdLedgerRouteImport.update({
  id: '/customers/$id/ledger',
  path: '/customers/$id/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdPaymentRoute = CustomersIdPaymentRouteImport.update({
  id: '/customers/$id/payment',
  path: '/customers/$id/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdPaymentsRoute = CustomersIdPaymentsRouteImport.update({
  id: '/customers/$id/payments',
  path: '/customers/$id/payments',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/delivery': typeof DeliveryRoute
  '/more': typeof MoreRoute
  '/reports': typeof ReportsRoute
  '/customers/new': typeof CustomersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/customers/$id/bill': typeof CustomersIdBillRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/customers/$id/ledger': typeof CustomersIdLedgerRoute
  '/customers/$id/payment': typeof CustomersIdPaymentRoute
  '/customers/$id/payments': typeof CustomersIdPaymentsRoute
  '/customers/$id/': typeof CustomersIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/delivery': typeof DeliveryRoute
  '/more': typeof MoreRoute
  '/reports': typeof ReportsRoute
  '/customers/new': typeof CustomersNewRoute
  '/customers': typeof CustomersIndexRoute
  '/customers/$id/bill': typeof CustomersIdBillRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/customers/$id/ledger': typeof CustomersIdLedgerRoute
  '/customers/$id/payment': typeof CustomersIdPaymentRoute
  '/customers/$id/payments': typeof CustomersIdPaymentsRoute
  '/customers/$id': typeof CustomersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/delivery': typeof DeliveryRoute
  '/more': typeof MoreRoute
  '/reports': typeof ReportsRoute
  '/customers/new': typeof CustomersNewRoute
  '/customers/': typeof CustomersIndexRoute
  '/customers/$id/bill': typeof CustomersIdBillRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/customers/$id/ledger': typeof CustomersIdLedgerRoute
  '/customers/$id/payment': typeof CustomersIdPaymentRoute
  '/customers/$id/payments': typeof CustomersIdPaymentsRoute
  '/customers/$id/': typeof CustomersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/billing'
    | '/delivery'
    | '/more'
    | '/reports'
    | '/customers/new'
    | '/customers/'
    | '/customers/$id/bill'
    | '/customers/$id/edit'
    | '/customers/$id/ledger'
    | '/customers/$id/payment'
    | '/customers/$id/payments'
    | '/customers/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/delivery'
    | '/more'
    | '/reports'
    | '/customers/new'
    | '/customers'
    | '/customers/$id/bill'
    | '/customers/$id/edit'
    | '/customers/$id/ledger'
    | '/customers/$id/payment'
    | '/customers/$id/payments'
    | '/customers/$id'
  id:
    | '__root__'
    | '/'
    | '/billing'
    | '/delivery'
    | '/more'
    | '/reports'
    | '/customers/new'
    | '/customers/'
    | '/customers/$id/bill'
    | '/customers/$id/edit'
    | '/customers/$id/ledger'
    | '/customers/$id/payment'
    | '/customers/$id/payments'
    | '/customers/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillingRoute: typeof BillingRoute
  DeliveryRoute: typeof DeliveryRoute
  MoreRoute: typeof MoreRoute
  ReportsRoute: typeof ReportsRoute
  CustomersNewRoute: typeof CustomersNewRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  CustomersIdBillRoute: typeof CustomersIdBillRoute
  CustomersIdEditRoute: typeof CustomersIdEditRoute
  CustomersIdLedgerRoute: typeof CustomersIdLedgerRoute
  CustomersIdPaymentRoute: typeof CustomersIdPaymentRoute
  CustomersIdPaymentsRoute: typeof CustomersIdPaymentsRoute
  CustomersIdIndexRoute: typeof CustomersIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/': {
      id: '/customers/$id/'
      path: '/customers/$id'
      fullPath: '/customers/$id/'
      preLoaderRoute: typeof CustomersIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/bill': {
      id: '/customers/$id/bill'
      path: '/customers/$id/bill'
      fullPath: '/customers/$id/bill'
      preLoaderRoute: typeof CustomersIdBillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/edit': {
      id: '/customers/$id/edit'
      path: '/customers/$id/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof CustomersIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/ledger': {
      id: '/customers/$id/ledger'
      path: '/customers/$id/ledger'
      fullPath: '/customers/$id/ledger'
      preLoaderRoute: typeof CustomersIdLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/payment': {
      id: '/customers/$id/payment'
      path: '/customers/$id/payment'
      fullPath: '/customers/$id/payment'
      preLoaderRoute: typeof CustomersIdPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id/payments': {
      id: '/customers/$id/payments'
      path: '/customers/$id/payments'
      fullPath: '/customers/$id/payments'
      preLoaderRoute: typeof CustomersIdPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillingRoute: BillingRoute,
  DeliveryRoute: DeliveryRoute,
  MoreRoute: MoreRoute,
  ReportsRoute: ReportsRoute,
  CustomersNewRoute: CustomersNewRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  CustomersIdBillRoute: CustomersIdBillRoute,
  CustomersIdEditRoute: CustomersIdEditRoute,
  CustomersIdLedgerRoute: CustomersIdLedgerRoute,
  CustomersIdPaymentRoute: CustomersIdPaymentRoute,
  CustomersIdPaymentsRoute: CustomersIdPaymentsRoute,
  CustomersIdIndexRoute: CustomersIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
